export const codes = {
    BAD_USER_INPUT: 'BAD_USER_INPUT',
    BAD_DESCRIPTION_INPUT: 'BAD_DESCRIPTION_INPUT',
    NOT_FOUND: 'NOT_FOUND',
    SERVER_ERROR: 'SERVER_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    DUPLICATED: 'DUPLICATED'
};