import type { Metadata } from "next";
import "@/styles/reset.css";
import "@/styles/base.css";

export const metadata: Metadata = {
	title: "Real time sport dashboard",
	description: "Generated by create next app",
};

const RootLayout = ({
  	children,
}: Readonly<{
  	children: React.ReactNode;
}>) => {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
};

export default RootLayout;